export const BB_DOC_LINES: string[] = [
  "#cWell we've reached the end of this demo. But #bnot#n the #bREAL END#n because",
  "",
  "#bAA PROJECT#n is here. ",
  "",
  "Please read curefully the following document for more information.",
  "",
  "#b*** This IS the FINAL2 version of BB, modded by stroucki ***#n",
  "",
  "#bCHECK OUT http://aa-project.sourceforge.net/#n",
  "",
  "First of all",
  "",
  "#bControls:#n",
  "",
  "f,space,down,j    page down",
  "b,up,k            page up  ",
  "q,esc             quit     ",
  "1,2,3             song     ",
  "",
  "#l",
  "#bContents:#n",
  "",
  "o  Advanced usage of this demo",
  "o  Personal greetings         ",
  "o  AA PROJECT                 ",
  "o  Available programs         ",
  "   o  Aview                   ",
  "   o  XaoS                    ",
  "   o  aaflip                  ",
  "o  The AA-Lib                 ",
  "o  The history                ",
  "#c",
  "#l",
  "#c#bAdvanced usage of this demo",
  "",
  "           XXXXXXX ",
  "           XX    XX",
  "XXXXXXX    XX    XX",
  "XX    XX   XXXXXXX ",
  "XX    XX   XX    XX",
  "XXXXXXX    XX    XX",
  "XX    XX   XXXXXXX ",
  "XX    XX           ",
  "XXXXXXX            #n",
  "",
  "#c",
  "#fYou can tune the demo using command line options:",
  "type bb --help | more   to get all available BB options",
  "",
  "We can recommend to you the following combinations:",
  "",
  "bb -loop -extended -reverse",
  "bb -loop -reverse -nobold -nonormal -nodim",
  "bb -loop -nodim -nobold -extended",
  "bb -driver stdout -width 79",
  "bb -driver stdout -width 79 > lpt1 (for some screenshots :)",
  "",
  "The option #bfont#n is usefull on hardware where AA-Lib is unable to get current font (like text terminals, mda etc..)",
  "",
  "",
  "Note: the most of this options are common to all #bAA Project#n programs.",
  "",
  "#f#l",
  "#c#bSome BB rumours#n",
  "",
  "It was expected to be in SuperVGA mode, truecolor, two CDs",
  "",
  "#bPersonal greetings#n",
  "",
  "#bHH#n:",
  "",
  "#bJaroslav Kysela#n",
  "I spent three hours patching koules for your drivers..I vote for #bsmaler fragments#n!",
  "#bMartin Mares#n",
  "What about searching alg for AAlib?",
  "#b0rfelyus#n",
  "be patient..",
  "#bRoman Zenka",
  "#nYou are in credits again :)",
  "#bFilip Kroluper#n",
  "Is YOUR AAlib ready?",
  "#bRobert Spalek#n",
  "Lend me your MetafontBook please..",
  "#bPetr Holicky#n",
  "I #bLOVE#n your mathematical analyzis lessons!",
  "",
  "#bKT#n:",
  "",
  "#bReni#n",
  "All I need is love...",
  "#bPetr Koloros#n",
  "What about your songs ?",
  "#bMartin Koloros#n",
  "Hey, have you finished Caynis ?",
  "#bVaclav Tesinsky#n",
  "I'll join your Delta club",
  "#bMartin Uddin#n",
  "Release your adventure game",
  "#bPetr Smejkal#n",
  "Still writing those databases, huh ?",
  "#bMichal Drda#n",
  "Remove w95 and install Plan9",
  "#bMichael W. Cerny#n",
  "Sport!",
  "#bJaroslav Kysela#n",
  "Hard coding for your drivers....:)",
  "",
  "#bMS#n:",
  "",
  "#bDenthor/Asphyxia#n",
  "yar tutors R the kewlest ones",
  "#bBLACKAXE#n",
  "i'll buy U a flask of Absinth !",
  "#b_MAD#n",
  "thanq 4 all help",
  "#bHeadSoft#n",
  "nice 2 meet ya",
  "#bSqrt(-1)#n",
  "hey, dude, thank 4 all ya've done 4 me",
  "#bQwert#n",
  "I love you, my dear friend - remember : next year ... ;-)",
  "#bHeroin#n",
  "Hey U, Sexual maniac !?",
  "#bKanec#n",
  "Don't drink so much !",
  "#bMarek Les#n",
  "Hope hear soon your new song !",
  "#bAnton Szandor LaVey#n",
  "thanx for The Satanic Bible",
  "#bMarquis de Sade#n",
  "big kisses for new style of life",
  "#bTrent Reznor#n",
  "the kewlest muzak i've ever heard",
  "#bJean-Philippe Couasnard#n",
  "hey, friend .. i hope ya stay here !",
  "#bMartin Literak#n",
  "hey, we will fuck them all (but only girls, okay ?)",
  "",
  "#bFK#n:",
  "",
  "#bEva Stroblova#n",
  "I want you to want me just like I want you.",
  "Carry on loving me",
  "#bWarlord/Scrymag#n",
  "Haven't you forgotten to close your mouth?",
  "#bPsycho/Scrymag#n",
  "Get Psyched!",
  "#bSmall Electric#n",
  "Don't you think that 300W sound in your room is too little ?",
  "#bSystem Trooper/STC#n",
  "Less Prodigy, more Dawn Music.",
  "#bM.D.A.#n",
  "Hey, I'm Samsa incompatible!",
  "#bVTM/Scrymag#n",
  "GUS !!!",
  "#bMamut#n",
  "No smoking, please.",
  "#bPurple Motion#n",
  "Your INSIDE.S3M made me start writting music",
  "#bJeffrey Lim#n",
  "Many thanx for Impulse Tracker",
  "",
  "",
  "#l",
  "#bAA-Project#n",
  "#c",
  "#bThree goals of AA-Project:#n",
  "",
  "#f1)Port all important software (like Doom, Second Reality, X windows etc..) on new AA-lib.",
  "",
  "2)Port AA-lib on all available platforms (mainly ZX-Spectrum and Sharp).",
  "",
  "3)Force IBM to start manufacturing MDA cards again.",
  "",
  "AA-project was started by Jan Hubicka. In that times just few people knew about ",
  "it. Then a new demo named BB has been relased to show the power ",
  "of AA-lib technology. Now the project is freely available and anyone can help.",
  "",
  "Just browse our homepage at #bhttp://aa-project.sourceforge.net/#n. Ton of ",
  "examples of ascii-art generated by aalib, pointers to other AA-Project ",
  "resources etc. ",
  "        ",
  "   We decided to distribute all of our aa-related programs freely (see ",
  "COPYING for details). But if you want to help us develop more such software ",
  "send a small amount (or big one ;-) to AA/BB maintainer address: ",
  "",
  "Kamil Toman",
  "CS Armady 1930, Tabor",
  "390 03",
  "Czech republic",
  "",
  "and contact us at:",
  "",
  "kupsaf@feld.cvut.cz (Filip Kupsa)",
  "hubicka@freesoft.cz (Jan Hubicka)",
  "titania@horac.ta.jcu.cz (Mojmir Svoboda)",
  "toman@artax.karlin.mff.cuni.cz (Kamil Toman)",
  "#f",
  "#l",
  "#c#bAvailable programs#n",
  "#c",
  "#fThis part contains a listing of programs currently avilable for #bAA-Lib#n. Note that it is probably outdated now. So look at #bhttp://aa-project.sourceforge.net/#n to get latest information#f",
  "",
  "",
  "",
  "#c#b      dT8  8     dP ",
  "     dT 8  8    dP  ",
  "    dT  8  8   dP   ",
  " <PROJECT> 8  dP    ",
  "  dT    8  8 dP     ",
  " dT     8  8XP Aview",
  "",
  "",
  "#c#f#nThis has been historically the first program developed for AA-Lib. In fact it is even older than AA-Lib itself and AA-Lib was later seperated from Aview sources. It was programmed to convert Linux Texas group #bpenguin logo#n to #bascii art#n. It has become powerful #bimage browser#n soon. It is extremly useful in combination of lynx-the best web browser. ",
  "",
  "Aview has some extended features (including text mode of course) most notably: possibility to #bsave various text formats#n including #bHTML, ANSI terminal escape sequences, Netscapized HTML, pure text file, UNIX more/less format printing to HP-Laser Jet and many others.#n Another useful feature are #bfast image scaling routines#n that automatically scale image to your favorite text resolutions; also controls for all #bAA-Lib features#n are available (including#b contrast, brightness, gamma correction, dithering modes, inversion, font selection, random dithering value#n#f",
  "",
  "#c#bXX   XX                 XXXXX ",
  " XX XX   XXXX    XXXX  XX     ",
  "  XXX   XX  XX  XX  XX  XXXXX ",
  " XX XX  XXXXXX  XX  XX      XX",
  "XX   XX XX  XX   XXXX   XXXXX #n",
  "#c",
  "#fXaoS is a #bfast portable realtime interactive fractal zoomer/morpher#n. It was the first program for AA routines in animation style. Current version (2.2) does not contain fully featured support for AA-Lib but it uses its own simplier and less portable routines (it is older than AA-Lib). But AA driver will be available soon after releasing BB. So check out XaoS homepage (http://www.tedium.com/XaoS) for more details #f",
  "",
  "#b#cXXXXXX XX      XX   XXXXXX ",
  "XX     XX      XX   XX   XX",
  "XXXX   XX      XX   XXXXXX ",
  "XX     XX      XX   XX     ",
  "XX     XXXXXXX XX   XX     #n",
  "#c",
  "#fFlip is an #bfli/flc player#n originally developed for linux/SVGAlib. A version ported toAA-Lib is available too (called #baaflip#n). It is portable and it works at MS-DOS and probably other architectures too. It supports fullscreen playing of animations, interactive changing of #bbrightness, contrast, gamma correction, value for random dithering.#f",
  "",
  "#l",
  "#c#bThe AA-Lib#n",
  "#f#c",
  "AA-lib is a low level gfx library just as many other libraries are. The ",
  "main difference is that AA-lib does not require graphics device. In fact, ",
  "there is no graphical output possible. AA-lib replaces those old-fashioned ",
  "output methods with powerful ascii-art renderer. Now my linux boots ",
  "with a nice penguin logo at secondary display (yes! Like Win95 does:) ",
  "AA-lib API is designed to be similar to other graphics libraries. Learning ",
  "a new API would be a piece of cake! ",
  "#f",
  "",
  "#l",
  "#c#bThe history#n",
  "#f",
  "Once upon a time we've (my friend Kamil and I) bought two old Herculeses ",
  "as secondary monitors. We didn't know for that time that our Diamond ",
  "Stealths 64 cards would become obsolete soon. Next day we downloaded ",
  "the logo of Linux Texas Users Group ",
  "- nice silly penguin looking like a cowboy! It was so exciting logo ... we ",
  "decided that we couldn't live without it and we wanted to see it every time ",
  "at a boot time as a logo on our secondary monitors. There was a small problem ",
  "- Hercules doesn't support color graphics. So we decided to convert an image ",
  "to ascii art using netpbm tools.",
  "",
  "The output was very ugly because the converting algorithm was absolutly stupid. ",
  "During the night I designed a new convertor that used a font bitmap for ",
  "creating aproximation table. The output wasn't very good since the algorithm ",
  "wasn't so well tuned. Many months this small piece of code was waiting on my ",
  "disc for the day \\\"D\\\". Meanwhile I started a new project XaoS (a fractal zoomer) ",
  "with my friend Thomas. And then I got an idea: Ascii Art Mandelbrots! ",
  "I was really impressed by the result! XaoS was faster, portable and looking ",
  "much better than ever before. I found a new way to go... #c",
  "#f",
  "",
  "",
  "",
  "#b#cAnd remember...",
  "                    ",
  "      dT8  8Tb      ",
  "     dT 8  8 Tb     ",
  "    dT  8  8  Tb    ",
  " <PROJECT><PROJECT> ",
  "  dT    8  8    Tb  ",
  " dT     8  8     Tb ",
  "",
  "...means Ascii art!",
  "#c\"",
  ""
];
